[package]
name = "zestors-actor"
version = "0.1.0"
edition = "2024"

[dependencies]
zestors-runtime.workspace = true
zestors-interface.workspace = true
futures.workspace = true
rootcause.workspace = true
zestors-codegen.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
zestors = { path = "../zestors" }