[package]
name = "zestors-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.48"
quote = "1.0.20"
proc-macro2 = "1.0.20"

[lib]
proc-macro = true

[dev-dependencies]
zestors = { path = "../zestors" }