[package]
name = "zestors"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A simple, fast and flexible actor framework for building robust distributed applications, heavily insipired by Erlang."
# homepage = 


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1", features = ["full"] }
futures = "^0.3"
async-trait = "^0.1"
anyhow = "^1"
oneshot = "^0.1"
async-channel = "1.6"
zestors-codegen = { path = "../zestors-codegen" }
# indexmap = "1.8"

[dev-dependencies]
derive_more = "^0.99"
