[workspace]
resolver = "3"
members = [
  "crates/codegen",
  "crates/zestors",
  "crates/inspector",
  "crates/runtime",
  "crates/api-server",
  "crates/supervision",
  "crates/actor",
  "crates/interface",
  "crates/supervisor",
  "crates/distr",
  "crates/distr-backend",
  "crates/distr-quic",
  "book",
]


[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Zestors/zestors"
homepage = "https://zestors.github.io/zestors/"
authors = ["Jasper van der Werf"]
keywords = ["actor", "actor-system", "tokio", "supervision", "distributed"]
categories = ["concurrency", "asynchronous"]

[workspace.dependencies]
zestors-inspector = { path = "crates/inspector", version = "0.2.0" }

zestors-codegen = { path = "crates/codegen", version = "0.2.0" }
zestors = { path = "crates/zestors", version = "0.2.0" }
zestors-runtime = { path = "crates/runtime", version = "0.2.0" }
zestors-api-server = { path = "crates/api-server", version = "0.2.0" }
zestors-supervision = { path = "crates/supervision", version = "0.2.0" }
zestors-actor = { path = "crates/actor", version = "0.2.0" }
zestors-interface = { path = "crates/interface", version = "0.2.0" }
zestors-supervisor = { path = "crates/supervisor", version = "0.2.0" }
zestors-distr = { path = "crates/distr", version = "0.2.0" }
zestors-distr-backend = { path = "crates/distr-backend", version = "0.2.0" }
zestors-distr-quic = { path = "crates/distr-quic", version = "0.2.0" }


type-sets = { version = "0.2.2" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
thiserror = "2"
tracing = "0.1"
rootcause = "0.13"
indexmap = "2"
smol_str = { version = "0.3", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
papaya = { version = "0.2", features = ["serde"] }
dashmap = "6"
inventory = "0.3"
rand = { version = "0.10" }
uuid = { version = "1", features = ["v4"] }
bs58 = { version = "0.5" }
axum = { version = "0.8", features = ["macros"]}
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
concurrent-queue = "2"
eyeball = "0.8"
jiff = { version = "0.2", features = ["serde"] }
reqwest = { version = "0.13" }
axum-typed-routing = { version = "0.4.6" }
streamunordered = "0.5"
quinn = "0.11"
foca = { version = "2", features = ["std", "postcard-codec", "tracing"] }
bytes = "1"
rcgen = "0.14"
rustls-webpki = { version = "0.103", default-features = false, features = ["std", "ring"] }


[workspace.metadata.release]
rate-limit = { existing-packages = 10 }
