[workspace]
resolver = "3"
members = [
  "crates/codegen",
  "crates/zestors",
  "crates/inspector",
  "crates/runtime",
  "crates/api-server",
  "crates/supervision",
  "crates/actor",
  "crates/interface",
  "crates/supervisor",
]


[workspace.dependencies]
zestors-inspector = { path = "crates/inspector", version = "0.2.0" }

zestors-codegen = { path = "crates/codegen", version = "0.2.0" }
zestors = { path = "crates/zestors", version = "0.2.0" }
zestors-runtime = { path = "crates/runtime", version = "0.2.0" }
zestors-api-server = { path = "crates/api-server", version = "0.2.0" }
zestors-supervision = { path = "crates/supervision", version = "0.2.0" }
zestors-actor = { path = "crates/actor", version = "0.2.0" }
zestors-interface = { path = "crates/interface", version = "0.2.0" }
zestors-supervisor = { path = "crates/supervisor", version = "0.2.0" }


type-sets = { version = "0.2.2" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
thiserror = "2"
tracing = "0.1"
rootcause = "0.13"
indexmap = "2"
smol_str = { version = "0.3", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
papaya = { version = "0.2", features = ["serde"] }
rand = { version = "0.10" }
bs58 = { version = "0.5" }
axum = { version = "0.8", features = ["macros"]}
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
concurrent-queue = "2"
eyeball = "0.8"
jiff = { version = "0.2", features = ["serde"] }
reqwest = { version = "0.13" }
axum-typed-routing = { version = "0.4.6" }
streamunordered = "0.5"

