[package]
name = "zestors-core"
version = "0.0.1"
edition = "2021"

[dependencies]
tiny-actor = { version = "^0.2", features = ["internals"] }
futures = "^0.3"
tokio = { version = "^1", features = ["full"] }
thiserror = "^1"

[features]
actor_types = []