[package]
name = "zestors-core"
version = "0.1.0"
edition = "2024"

[dependencies]
zestors-codegen.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
rootcause.workspace = true
thiserror.workspace = true
indexmap.workspace = true
smol_str.workspace = true
type-sets.workspace = true
serde.workspace = true
papaya.workspace = true
axum-autoroute.workspace = true
zestors-runtime.workspace = true
jiff.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
