[package]
name = "zestors"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "An actor framework with Erlang/OTP-style supervision"
repository = "https://github.com/Zestors/zestors"

[dependencies]
zestors-supervision.workspace = true
zestors-runtime.workspace = true
zestors-actor.workspace = true
zestors-api-server.workspace = true
zestors-codegen.workspace = true
zestors-interface.workspace = true
zestors-supervisor.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
rootcause.workspace = true

[features]
_ra = []
