[package]
name = "zestors-distr-quic"
version = "0.3.0"
edition = "2024"
readme = "README.md"
description = "A QUIC backend with mutual TLS for zestors-distr clusters"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zestors-distr-backend.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls-webpki.workspace = true
bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tokio-util = { version = "0.7", features = ["time"] }
