[package]
name = "zestors-api-server"
version = "0.1.0"
edition = "2024"

[dependencies]
zestors-runtime.workspace = true
zestors-supervision.workspace = true
zestors-actor.workspace = true
zestors-codegen.workspace = true
tracing.workspace = true
axum.workspace = true
tokio.workspace = true
smol_str.workspace = true
rootcause.workspace = true
futures.workspace = true
axum-typed-routing.workspace = true
indexmap = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
