[package]
name = "zestors-api-server"
version = "0.3.0"
edition = "2024"
readme = "README.md"
description = "HTTP introspection server for the zestors actor framework"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zestors-runtime.workspace = true
zestors-supervision.workspace = true
zestors-actor.workspace = true
zestors-codegen.workspace = true
zestors-interface.workspace = true
tracing.workspace = true
axum.workspace = true
tokio.workspace = true
rootcause.workspace = true
futures.workspace = true
axum-typed-routing.workspace = true
indexmap = { workspace = true, features = ["serde"] }
axum-error-sets = { version = "0.4"}