[package]
name = "zestors-inspector"
version.workspace = true
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "GUI inspector for a running zestors actor tree"
repository = "https://github.com/Zestors/zestors"

[dependencies]
eframe = { version = "0.36.1", features = ["glow", "__screenshot"] }
env_logger = { version = "0.11", features = ["auto-color", "humantime"] }
egui_extras = { version = "0.36", features = ["default", "image"] }
egui_glow = { version = "0.36", features = [] }
egui = { version = "0.36", features = [] }
tokio = { workspace = true, features = ["full"] }
rootcause = { workspace = true }
futures = { workspace = true }
zestors = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
indexmap = { workspace = true }

[features]
_ra = []
