[package]
name = "zestors-inspector"
version = "0.3.0"
edition = "2024"
readme = "README.md"
description = "GUI inspector for a running zestors actor tree"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
eframe = { version = "0.36.1", features = ["glow", "__screenshot"] }
env_logger = { version = "0.11", features = ["auto-color", "humantime"] }
egui_extras = { version = "0.36", features = ["default", "image"] }
egui = { version = "0.36", features = [] }
tokio = { workspace = true, features = ["full"] }
rootcause = { workspace = true }
futures = { workspace = true }
zestors = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
indexmap = { workspace = true }

[features]
_ra = []
