[package]
name = "zestors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zestors-codegen = { path = "../zestors-codegen" }
zestors-core = { path = "../zestors-core" }
futures = "0.3.0"
tokio = { version = "1.18", features = ["full"] }
thiserror = "1.0"
once_cell = "1.13"