[package]
edition = "2021"
name = "zestors"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1"
futures = "^0.3"
thiserror = "^1"
tiny-actor = {version = "^0.2.1", features = ["internals"], path = "../../tiny-actor"}
tokio = {version = "^1", features = ["full"]}
# tiny-actor = { path = "../../ActorSystem/tiny-actor", features = ["internals"] }
anyhow = "1.0.68"
bincode = "1.3.3"
bytes = "1.2.1"
pin-project = "1.0.12"
serde = {version = "^1", features = ["derive"]}
tokio-util = {version = "0.6.4", features = ["codec"]}
uuid = {version = "1.0", features = ["v4"]}
zestors-codegen = {path = "../zestors-codegen"}
# concurrent-queue = "2.0.0"
# event-listener = "2.5.3"
# spin_sleep = "1.1.1"

[dev-dependencies]
