[package]
name = "zestors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zestors-codegen = "0.0.3"
zestors-core = "0.0.1"
zestors-request = { path = "../zestors-request" }

[dev-dependencies]
async-trait = "0.1.57"
futures = "^0.3.0"
tokio = { version = "1.18", features = ["full"] }
