[package]
name = "zestors"
version = "0.0.2"
edition = "2021"

license = "MIT OR Apache-2.0"
description = "A fast, flexible and extensible actor-framework."
repository = "https://github.com/Zestors/zestors"
homepage = "https://github.com/Zestors/zestors"
keywords = ["actor", "actor-system", "tokio", "pool"]
categories = ["concurrency"]
authors = ["jvdwrf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zestors-codegen = { path = "../zestors-codegen" }
zestors-core = { path = "../zestors-core" }
zestors-request = { path = "../zestors-request" }

[dev-dependencies]
async-trait = "0.1.57"
futures = "^0.3.0"
tokio = { version = "1.18", features = ["full"] }
