[package]
name = "zestors-codegen"
version.workspace = true
edition = "2021"
repository = "https://github.com/Zestors/zestors"
homepage = "https://github.com/Zestors/zestors"
authors = ["Jasper van der Werf"]
license = "MIT OR Apache-2.0"
description = "Derive macros for the zestors actor framework"
keywords = ["actor", "actor-system", "tokio"]
categories = ["concurrency"]
readme = "README.md"

[dependencies]
syn = { version = "3", features = ["full"] }
quote = "1"
proc-macro2 = "1"
heck = "0.5"
darling = { version = "0.24" }

[dev-dependencies]
zestors-interface = { path = "../interface" }

[lib]
proc-macro = true
