[package]
name = "zestors-codegen"
version = "0.2.0"
edition = "2021"
description = "Derive macros for the zestors actor framework"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
syn = { version = "3", features = ["full"] }
quote = "1"
darling = { version = "0.24" }
uuid = { version = "1", features = ["v4"] }
proc-macro2 = "1"

[dev-dependencies]
zestors = { path = "../zestors" }
zestors-interface = { path = "../interface" }
zestors-distr = { path = "../distr" }
rootcause = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["zestors", "zestors-interface", "zestors-distr", "rootcause"] # only used in doctests

[lib]
proc-macro = true
