[package]
name = "zestors-distr-backend"
version = "0.2.0"
edition = "2024"
readme = "README.md"
description = "The transport interface of zestors-distr clusters"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde.workspace = true
smol_str.workspace = true
tokio.workspace = true
bytes.workspace = true
