[package]
name = "zestors-interface"
version = "0.2.0"
edition = "2024"
readme = "README.md"
description = "Message/Interface vocabulary for the zestors actor framework"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
type-sets.workspace = true
futures.workspace = true
tokio.workspace = true
thiserror.workspace = true
zestors-codegen.workspace = true
tracing.workspace = true

[dev-dependencies]
zestors-codegen = { path = "../codegen" }
zestors = { path = "../zestors" }

[package.metadata.cargo-machete]
ignored = ["zestors"] # only used in doctests