[package]
name = "zestors-interface"
version.workspace = true
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Message/Interface vocabulary for the zestors actor framework"
repository = "https://github.com/Zestors/zestors"

[dependencies]
type-sets.workspace = true
futures.workspace = true
tokio.workspace = true
thiserror.workspace = true
zestors-codegen.workspace = true
tracing.workspace = true

[dev-dependencies]
zestors-codegen = { path = "../codegen" }
zestors = { path = "../zestors" }